#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 19, 2019 02:59:07 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import operations_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    operations_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    operations_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("900x500+200+100")
        top.title("Operations")
        top.configure(background="#ffaa00")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.044, rely=0.057, relheight=0.872
                , relwidth=0.917)
        self.Frame1.configure(relief='flat')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(background="#ffffff")
        self.Frame1.configure(width=825)

        self.Message1 = tk.Message(self.Frame1)
        self.Message1.place(relx=0.4, rely=0.044, relheight=0.073
                , relwidth=0.182)
        self.Message1.configure(background="#ffffff")
        self.Message1.configure(font="-family {Consolas} -size 14 -weight bold")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''Operations -->''')
        self.Message1.configure(width=150)

        self.Message2 = tk.Message(self.Frame1)
        self.Message2.place(relx=0.180, rely=0.132, relheight=0.073
                , relwidth=0.655)
        self.Message2.configure(background="#ffffff")
        self.Message2.configure(font="-family {Consolas} -size 12 -weight bold -slant italic")
        self.Message2.configure(foreground="#000000")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="black")
        self.Message2.configure(text='''CLICK on OPERATION as your wish on default file (data.txt)''')
        self.Message2.configure(width=540)

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.109, rely=0.308, height=64, width=157)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#e5ffc7")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 12 -slant italic")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(relief="flat")
        self.Button1.configure(text='''Show Data''')
        self.Button1.configure(width=157)

        self.Message3 = tk.Message(self.Frame1)
        self.Message3.place(relx=0.036, rely=0.791, relheight=0.051
                , relwidth=0.921)
        self.Message3.configure(background="#ffffff")
        self.Message3.configure(font="-family {Consolas} -size 12 -underline 1")
        self.Message3.configure(foreground="#000000")
        self.Message3.configure(highlightbackground="#d9d9d9")
        self.Message3.configure(highlightcolor="black")
        self.Message3.configure(text='''-----------------------------------------------------------------------------------''')
        self.Message3.configure(width=760)

        self.Button2 = tk.Button(self.Frame1)
        self.Button2.place(relx=0.4, rely=0.308, height=64, width=157)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#e5ffc7")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Segoe UI} -size 12 -slant italic")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(relief="flat")
        self.Button2.configure(text='''Load Data to Tree''')

        self.Button3 = tk.Button(self.Frame1)
        self.Button3.place(relx=0.691, rely=0.308, height=64, width=157)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#e5ffc7")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font="-family {Segoe UI} -size 12 -slant italic")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(relief="flat")
        self.Button3.configure(text='''Search a Record''')

        self.Button4 = tk.Button(self.Frame1)
        self.Button4.place(relx=0.109, rely=0.549, height=64, width=157)
        self.Button4.configure(activebackground="#ececec")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#88ff00")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(font="-family {Segoe UI} -size 12 -slant italic")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(relief="flat")
        self.Button4.configure(text='''Add New Record''')


        self.Button5 = tk.Button(self.Frame1)
        self.Button5.place(relx=0.4, rely=0.549, height=64, width=157)
        self.Button5.configure(activebackground="#ececec")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="#78dbff")
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(font="-family {Segoe UI} -size 12 -slant italic")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")
        self.Button5.configure(relief="flat")
        self.Button5.configure(text='''Modify a Record''')


        self.Button6 = tk.Button(self.Frame1)
        self.Button6.place(relx=0.691, rely=0.549, height=64, width=157)
        self.Button6.configure(activebackground="#ececec")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#ff7d7d")
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(font="-family {Segoe UI} -size 12 -slant italic")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(pady="0")
        self.Button6.configure(relief="flat")
        self.Button6.configure(text='''Delete a Record''')


        self.Button7 = tk.Button(self.Frame1)
        self.Button7.place(relx=0.788, rely=0.879, height=34, width=137)
        self.Button7.configure(activebackground="#ececec")
        self.Button7.configure(activeforeground="#000000")
        self.Button7.configure(background="#e5ffc7")
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(font="-family {Segoe UI} -size 12 -slant italic")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="black")
        self.Button7.configure(pady="0")
        self.Button7.configure(relief="flat")
        self.Button7.configure(text='''Goto Index Page''')
        self.Button7.configure(width=137)

        self.Button1.configure(command=self.showData)
        self.Button2.configure(command=self.loadData)
        self.Button3.configure(command=self.searchRecord)
        self.Button4.configure(command=self.addRecord)
        self.Button5.configure(command=self.modifyRecord)
        self.Button6.configure(command=self.deleteRecord)
        self.Button7.configure(command=self.goToIndex)


    def showData(self):
        os.system('python currentdata.py')

    def loadData(self):
        pass
        # root.destroy()
        # os.system('python operations.py')

    def searchRecord(self):
        root.destroy()
        os.system('python search.py')

    def addRecord(self):
        root.destroy()
        os.system('python operations.py')

    def modifyRecord(self):
        root.destroy()
        os.system('python modify.py')

    def deleteRecord(self):
        root.destroy()
        os.system('python delete.py')

    def goToIndex(self):
        root.destroy()
        os.system('python index.py')

if __name__ == '__main__':
    vp_start_gui()
