#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  May 19, 2019 06:43:59 PM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family Consolas -size 14 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family Consolas -size 14 -weight normal -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family Consolas -size 13 -weight normal -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family Consolas -size 12 -weight normal -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font13
vTcl:font:add_font \
    "-family Consolas -size 14 -weight normal -slant italic -underline 1 -overstrike 0" \
    user \
    vTcl:font14
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#ffaa00} 
    wm focusmodel $top passive
    wm geometry $top 900x500+200+100
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -background {#ffffff} -height 445 -width 845 
    vTcl:DefineAlias "$top.fra43" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra43
    label $site_3_0.lab44 \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 12 -slant italic} \
        -foreground {#000000} -justify left \
        -text {Enter the User ID to SEARCH :} 
    vTcl:DefineAlias "$site_3_0.lab44" "Label1" vTcl:WidgetProc "Toplevel1" 1
    message $site_3_0.mes45 \
        -background {#ffffff} \
        -font {-family {Consolas} -size 14 -slant italic -underline 1} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {SEARCH OPERATION} -width 374 
    vTcl:DefineAlias "$site_3_0.mes45" "Message1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent46 \
        -background {#edffba} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 14 -slant italic} \
        -foreground {#000000} -insertbackground black -relief flat 
    vTcl:DefineAlias "$site_3_0.ent46" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis52 \
        -background {#edffba} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 14} -foreground {#000000} -height 232 \
        -relief flat -width 764 
    .top42.fra43.lis52 configure -font "-family {Consolas} -size 14"
    .top42.fra43.lis52 insert end text
    vTcl:DefineAlias "$site_3_0.lis52" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but54 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#ade1ff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 13 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -relief flat -text Button 
    vTcl:DefineAlias "$site_3_0.but54" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but55 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#ade1ff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 13 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -relief flat -text {Back to Options} 
    vTcl:DefineAlias "$site_3_0.but55" "Button1_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab44 \
        -in $site_3_0 -x 40 -y 60 -width 284 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes45 \
        -in $site_3_0 -x 240 -y 20 -width 374 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 340 -y 60 -width 214 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lis52 \
        -in $site_3_0 -x 40 -y 130 -width 764 -relwidth 0 -height 232 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 610 -y 60 -width 187 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but55 \
        -in $site_3_0 -x 620 -y 390 -width 187 -height 34 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 30 -y 30 -width 845 -relwidth 0 -height 445 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

