#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 19, 2019 06:43:57 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import search_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    search_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    search_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("900x500+200+100")
        top.title("Search")
        top.configure(background="#ffaa00")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.033, rely=0.06, relheight=0.89, relwidth=0.939)
        self.Frame1.configure(relief='flat')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(background="#ffffff")
        self.Frame1.configure(width=845)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.047, rely=0.135, height=31, width=284)
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Consolas} -size 12 -slant italic")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(justify='left')
        self.Label1.configure(text='''Enter the User ID to SEARCH :''')
        self.Label1.configure(width=284)

        self.Message1 = tk.Message(self.Frame1)
        self.Message1.place(relx=0.284, rely=0.045, relheight=0.049
                , relwidth=0.443)
        self.Message1.configure(background="#ffffff")
        self.Message1.configure(font="-family {Consolas} -size 14 -slant italic -underline 1")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''SEARCH OPERATION''')
        self.Message1.configure(width=374)

        self.Entry1 = tk.Entry(self.Frame1)
        self.Entry1.place(relx=0.402, rely=0.135,height=30, relwidth=0.253)
        self.Entry1.configure(background="#edffba")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="-family {Consolas} -size 14 -slant italic")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(relief="flat")
        self.Entry1.configure(width=214)

        self.Listbox1 = tk.Listbox(self.Frame1)
        self.Listbox1.place(relx=0.047, rely=0.292, relheight=0.521
                , relwidth=0.904)
        self.Listbox1.configure(background="#edffba")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="-family {Consolas} -size 14")
        self.Listbox1.configure(foreground="#000000")
        self.Listbox1.configure(relief="flat")
        self.Listbox1.configure(width=764)

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.722, rely=0.135, height=34, width=187)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#ade1ff")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Consolas} -size 13 -slant italic")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(relief="flat")
        self.Button1.configure(text='''Search''')
        self.Button1.configure(width=187)

        self.Button1_1 = tk.Button(self.Frame1)
        self.Button1_1.place(relx=0.734, rely=0.876, height=34, width=187)
        self.Button1_1.configure(activebackground="#ececec")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#ade1ff")
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font="-family {Consolas} -size 13 -slant italic")
        self.Button1_1.configure(foreground="#000000")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(relief="flat")
        self.Button1_1.configure(text='''Back to Options''')

if __name__ == '__main__':
    vp_start_gui()
