#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 21, 2019 03:32:04 PM IST  platform: Windows NT

import sys
import os
import numpy as np
import pandas as pd

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import search_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    search_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    search_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("900x500+200+100")
        top.title("Search")
        top.configure(background="#ffaa00")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.033, rely=0.06, relheight=0.89, relwidth=0.939)
        self.Frame1.configure(relief='flat')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(background="#ffffff")
        self.Frame1.configure(width=845)

        self.Message1 = tk.Message(self.Frame1)
        self.Message1.place(relx=0.296, rely=0.045, relheight=0.074
                , relwidth=0.379)
        self.Message1.configure(background="#ffffff")
        self.Message1.configure(font="-family {Consolas} -size 14 -weight bold -slant italic -underline 1")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''SEARCH OPERATION''')
        self.Message1.configure(width=320)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.024, rely=0.18, height=31, width=284)
        self.Label1.configure(anchor='e')
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Consolas} -size 14 -slant italic")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Enter User ID to Search''')
        self.Label1.configure(width=284)

        self.Entry1 = tk.Entry(self.Frame1)
        self.Entry1.place(relx=0.379, rely=0.18,height=30, relwidth=0.265)
        self.Entry1.configure(background="#e8fff8")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="-family {Consolas} -size 14 -slant italic")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(relief="groove")
        self.Entry1.configure(width=224)

        self.Listbox1 = tk.Listbox(self.Frame1)
        self.Listbox1.place(relx=0.071, rely=0.315, relheight=0.476
                , relwidth=0.857)
        self.Listbox1.configure(background="#e3fffb")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="-family {Consolas} -size 13 -slant italic")
        self.Listbox1.configure(foreground="#000000")
        self.Listbox1.configure(relief="flat")
        self.Listbox1.configure(width=724)

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.698, rely=0.18, height=34, width=187)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#00ffee")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Consolas} -size 14 -slant italic")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(relief="flat")
        self.Button1.configure(text='''Search''')
        self.Button1.configure(width=187)

        self.Button2 = tk.Button(self.Frame1)
        self.Button2.place(relx=0.734, rely=0.831, height=34, width=167)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#00ffee")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Consolas} -size 13 -slant italic")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(relief="flat")
        self.Button2.configure(text='''Go Back''')
        self.Button2.configure(width=167)

        self.Button1.configure(command=self.searchRecord)
        self.Button2.configure(command=self.goBack)

    def searchRecord(self):
        pass

    def goBack(self):
        root.destroy()
        os.system('python operations.py')

if __name__ == '__main__':
    vp_start_gui()
