#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  May 20, 2019 06:54:17 PM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family Consolas -size 12 -weight normal -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family Consolas -size 11 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family Consolas -size 13 -weight bold -slant italic -underline 1 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family Consolas -size 11 -weight normal -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#ffaa00} 
    wm focusmodel $top passive
    wm geometry $top 900x500+200+100
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Add New Record"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -background {#ffffff} -height 445 -width 845 
    vTcl:DefineAlias "$top.fra43" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra43
    label $site_3_0.lab45 \
        -anchor e -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -justify left -text {User ID} 
    vTcl:DefineAlias "$site_3_0.lab45" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent46 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove 
    vTcl:DefineAlias "$site_3_0.ent46" "Entry11" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab47 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text {Emp ID} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent49 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent49" "Entry01" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text {Name Prefix} 
    vTcl:DefineAlias "$site_3_0.lab51" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab52 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text {First Name} 
    vTcl:DefineAlias "$site_3_0.lab52" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text {Middle Initial} 
    vTcl:DefineAlias "$site_3_0.lab53" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab54 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Gender 
    vTcl:DefineAlias "$site_3_0.lab54" "Label7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text {Last Name} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text {E Mail} 
    vTcl:DefineAlias "$site_3_0.lab56" "Label8" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text {Mother's Name} 
    vTcl:DefineAlias "$site_3_0.lab57" "Label10" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab58 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text {Father's Name} 
    vTcl:DefineAlias "$site_3_0.lab58" "Label9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab59 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text {Age in Yrs} 
    vTcl:DefineAlias "$site_3_0.lab59" "Label11" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent60 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent60" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent61 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent61" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent62 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent62" "Entry6" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent63 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent63" "Entry8" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent64 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent64" "Entry7" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent65 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent65" "Entry10" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent66 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent66" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent67 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent67" "Entry9" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent68 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent68" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab69 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text {Age in Company (Years)} 
    vTcl:DefineAlias "$site_3_0.lab69" "Label13" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab70 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Salary 
    vTcl:DefineAlias "$site_3_0.lab70" "Label14" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab71 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text SSN 
    vTcl:DefineAlias "$site_3_0.lab71" "Label15" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab72 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text {Phone No} 
    vTcl:DefineAlias "$site_3_0.lab72" "Label16" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab73 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text City 
    vTcl:DefineAlias "$site_3_0.lab73" "Label17" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab74 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text State 
    vTcl:DefineAlias "$site_3_0.lab74" "Label18" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab75 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text ZIP 
    vTcl:DefineAlias "$site_3_0.lab75" "Label19" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab77 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text {Date of Joining} 
    vTcl:DefineAlias "$site_3_0.lab77" "Label12" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent78 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent78" "Entry12" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent79 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent79" "Entry13" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent80 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent80" "Entry14" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent81 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent81" "Entry15" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent82 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent82" "Entry16" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent83 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent83" "Entry17" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent84 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent84" "Entry18" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent85 \
        -background {#ebfffd} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -readonlybackground {#f0f0f0} -relief groove \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent85" "Entry19" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but87 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#88ff00} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 12 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -relief flat -text {Add Record} 
    vTcl:DefineAlias "$site_3_0.but87" "Button1" vTcl:WidgetProc "Toplevel1" 1
    message $site_3_0.mes89 \
        -background {#ffffff} \
        -font {-family {Consolas} -size 13 -weight bold -slant italic -underline 1} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Add New Record} -width 190 
    vTcl:DefineAlias "$site_3_0.mes89" "Message1_6" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab45 \
        -in $site_3_0 -x 20 -y 60 -width 184 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 230 -y 360 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 20 -y 90 -width 184 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent49 \
        -in $site_3_0 -x 230 -y 60 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 20 -y 120 -width 184 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 20 -y 150 -width 184 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 20 -y 180 -width 184 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 20 -y 240 -width 184 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 20 -y 210 -width 184 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 20 -y 270 -width 184 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 20 -y 330 -width 184 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 20 -y 300 -width 184 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 20 -y 360 -width 184 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent60 \
        -in $site_3_0 -x 230 -y 90 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent61 \
        -in $site_3_0 -x 230 -y 120 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent62 \
        -in $site_3_0 -x 230 -y 210 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent63 \
        -in $site_3_0 -x 230 -y 270 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent64 \
        -in $site_3_0 -x 230 -y 240 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent65 \
        -in $site_3_0 -x 230 -y 330 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent66 \
        -in $site_3_0 -x 230 -y 150 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent67 \
        -in $site_3_0 -x 230 -y 300 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent68 \
        -in $site_3_0 -x 230 -y 180 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 440 -y 90 -width 184 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 440 -y 120 -width 184 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 440 -y 150 -width 184 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 440 -y 180 -width 184 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 440 -y 210 -width 184 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 440 -y 240 -width 184 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab75 \
        -in $site_3_0 -x 440 -y 270 -width 184 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab77 \
        -in $site_3_0 -x 440 -y 60 -width 184 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent78 \
        -in $site_3_0 -x 650 -y 60 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent79 \
        -in $site_3_0 -x 650 -y 90 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent80 \
        -in $site_3_0 -x 650 -y 120 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent81 \
        -in $site_3_0 -x 650 -y 150 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent82 \
        -in $site_3_0 -x 650 -y 180 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent83 \
        -in $site_3_0 -x 650 -y 210 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent84 \
        -in $site_3_0 -x 650 -y 240 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent85 \
        -in $site_3_0 -x 650 -y 270 -width 144 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but87 \
        -in $site_3_0 -x 600 -y 340 -width 197 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes89 \
        -in $site_3_0 -x 310 -y 20 -width 190 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 30 -y 30 -width 845 -relwidth 0 -height 445 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

