#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 21, 2019 04:43:21 AM IST  platform: Windows NT

import sys
import os
import numpy as np
import pandas as pd
from backend.sbpt import Sbpt
from backend.alter import Alter

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import delete_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    delete_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    delete_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("900x500+200+100")
        top.title("Delete Record")
        top.configure(background="#ffaa00")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.033, rely=0.06, relheight=0.89, relwidth=0.939)
        self.Frame1.configure(relief='flat')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(background="#ffffff")
        self.Frame1.configure(width=845)

        self.Message1 = tk.Message(self.Frame1)
        self.Message1.place(relx=0.331, rely=0.09, relheight=0.074
                , relwidth=0.367)
        self.Message1.configure(background="#ff8282")
        self.Message1.configure(font="-family {Consolas} -size 14 -weight bold -underline 1")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''DELETE RECORDS''')
        self.Message1.configure(width=310)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.047, rely=0.337, height=31, width=244)
        self.Label1.configure(anchor='e')
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Consolas} -size 13")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Enter User ID to Delete''')
        self.Label1.configure(width=244)

        self.Entry1 = tk.Entry(self.Frame1)
        self.Entry1.place(relx=0.391, rely=0.337,height=30, relwidth=0.218)
        self.Entry1.configure(background="#d9fffe")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="-family {Consolas} -size 13 -weight bold")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=184)

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.686, rely=0.337, height=34, width=197)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#ff9191")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Consolas} -size 13")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(relief="flat")
        self.Button1.configure(text='''Delete''')
        self.Button1.configure(width=197)


        self.Message2 = tk.Message(self.Frame1)
        self.Message2.place(relx=0.237, rely=0.562, relheight=0.209
                , relwidth=0.521)
        # self.Message2.configure(background="#fff0f0")
        self.Message2.configure(background="#ffffff")
        self.Message2.configure(font="-family {Consolas} -size 13 -weight bold")
        self.Message2.configure(foreground="#ff2b2b")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="black")
        # self.Message2.configure(text='''Record with {} User ID has been Deleted''')
        self.Message2.configure(width=440)

        self.Button2 = tk.Button(self.Frame1)
        self.Button2.place(relx=0.45, rely=0.854, height=34, width=107)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#52e2ff")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Consolas} -size 13")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(relief="flat")
        self.Button2.configure(text='''Go Back''')
        self.Button2.configure(width=107)

        self.Button1.configure(command=self.deleteRecord)
        self.Button2.configure(command=self.goBack)

    def goBack(self):
        root.destroy()
        os.system('python operations.py')

    def deleteRecord(self):

        import random
        r1 = lambda: random.randint(10,15)
        r2 = lambda: random.randint(0,15)
        color = "#"+ str(hex(r1())[2:]) + str(hex(r2())[2:]) + str(hex(r1())[2:]) + str(hex(r2())[2:]) + str(hex(r1())[2:]) + str(hex(r2())[2:])

        var1 = self.Entry1.get()
        if var1 == '':
            self.Message2.configure(background=color)
            self.Message2.configure(text='''Fill the Form''')
        else:
            at = Alter()
            sp = Sbpt()
            file = "data.txt"
            t = sp.loadTree(file)
            ser = sp.search(t[0], var1)
            if ser[:2] == "NO":
                self.Message2.configure(background=color)
                text = "Record with { " + var1 + " } User ID Does Not Exist"
                self.Message2.configure(text=text)
                self.Entry1.delete(0, tk.END)
            else:
                id = at.delete(var1, file, True)
                self.Message2.configure(background=color)
                text = "Record with { " + id + " } User ID Has been DELETED"
                self.Message2.configure(text=text)
                self.Entry1.delete(0, tk.END)

if __name__ == '__main__':
    vp_start_gui()
