#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  May 19, 2019 12:45:09 PM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family Consolas -size 15 -weight normal -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family Consolas -size 20 -weight bold -slant italic -underline 1 -overstrike 0" \
    user \
    vTcl:font13
vTcl:font:add_font \
    "-family Consolas -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font17
vTcl:font:add_font \
    "-family Consolas -size 14 -weight bold -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font19
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m52" -background {#ffaa00} -highlightbackground {#ffffff} \
        -highlightcolor {#ffffff} 
    wm focusmodel $top passive
    wm geometry $top 600x450+446+175
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Simple Prefix B+ Tree"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra44 \
        -borderwidth 2 -background {#ffffff} -colormap {} -height 405 \
        -width 545 
    vTcl:DefineAlias "$top.fra44" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra44
    button $site_3_0.but48 \
        -activebackground {#6fedd8} -activeforeground {#000000} \
        -background {#0ab2ef} -disabledforeground {#a3a3a3} \
        -font {-family {Consolas} -size 12} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -relief flat -text {Get Inside} 
    vTcl:DefineAlias "$site_3_0.but48" "Button1" vTcl:WidgetProc "Toplevel1" 1
    message $site_3_0.mes49 \
        -background {#ffffff} \
        -font {-family {Consolas} -size 15 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify center \
        -text {By                      Shubham Anand {1BY16IS050}     Shreya Raj {1BY16IS048}} \
        -width 300 
    vTcl:DefineAlias "$site_3_0.mes49" "Message1" vTcl:WidgetProc "Toplevel1" 1
    message $site_3_0.mes50 \
        -background {#6fff00} \
        -font {-family {Consolas} -size 20 -weight bold -slant italic -underline 1} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {LOADING A SIMPLE PRIFIX B+ TREE} \
        -width 500 
    vTcl:DefineAlias "$site_3_0.mes50" "Message2" vTcl:WidgetProc "Toplevel1" 1
    message $site_3_0.mes51 \
        -background {#A1FFD3} \
        -font {-family {Consolas} -size 14 -weight bold -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify center \
        -text {Under the Guidance of Veena N               Asst. Prof, Dept of ISE} \
        -width 250 
    vTcl:DefineAlias "$site_3_0.mes51" "Message3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but48 \
        -in $site_3_0 -x 230 -y 330 -width 127 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes49 \
        -in $site_3_0 -x 120 -y 110 -width 300 -relwidth 0 -height 83 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes50 \
        -in $site_3_0 -x 20 -y 30 -width 500 -relwidth 0 -height 43 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes51 \
        -in $site_3_0 -x 150 -y 230 -width 250 -relwidth 0 -height 73 \
        -relheight 0 -anchor nw -bordermode ignore 
    set site_3_0 $top.m52
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra44 \
        -in $top -x 30 -y 20 -width 545 -relwidth 0 -height 405 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

