#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 19, 2019 12:45:07 PM IST  platform: Windows NT

import sys
import os

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import index_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    index_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    index_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'


        # def resize(event):
            # print("New size is: {}x{}".format(event.width, event.height))

        # top.bind("<Configure>", resize)
        # top.geometry("600x450+446+175")
        top.geometry("900x500+200+100")
        # top.geometry("1366x715+0+0")

        # top.attributes('-fullscreen', True)
        # top.geometry("{0}x{1}+0+0".format(
            # top.winfo_screenwidth(), top.winfo_screenheight()))
        top.title("Simple Prefix B+ Tree")
        top.configure(background="#ffaa00")
        top.configure(highlightbackground="#ffffff")
        top.configure(highlightcolor="#ffffff")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.044, rely=0.058, relheight=0.873, relwidth=0.917)
        self.Frame1.configure(relief='flat')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(background="#ffffff")
        self.Frame1.configure(width=545)

        self.Message1 = tk.Message(self.Frame1)
        self.Message1.place(relx=0.22, rely=0.272, relheight=0.205
                , relwidth=0.55)
        self.Message1.configure(background="#ffffff")
        self.Message1.configure(font="-family {Consolas} -size 15 -slant italic")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(justify='center')
        self.Message1.configure(text='''By                      Shubham Anand {1BY16IS050}     Shreya Raj {1BY16IS048}''')
        self.Message1.configure(width=300)

        self.Message2 = tk.Message(self.Frame1)
        self.Message2.place(relx=0.037, rely=0.074, relheight=0.106
                , relwidth=0.917)
        self.Message2.configure(background="#6fff00")
        self.Message2.configure(font="-family {Consolas} -size 20 -weight bold -slant italic -underline 1")
        self.Message2.configure(foreground="#000000")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="black")
        self.Message2.configure(text='''LOADING A SIMPLE PRIFIX B+ TREE''')
        self.Message2.configure(width=500)

        self.Message3 = tk.Message(self.Frame1)
        self.Message3.place(relx=0.275, rely=0.568, relheight=0.18
                , relwidth=0.459)
        self.Message3.configure(background="#A1FFD3")
        self.Message3.configure(font="-family {Consolas} -size 14 -weight bold -slant italic")
        self.Message3.configure(foreground="#000000")
        self.Message3.configure(highlightbackground="#d9d9d9")
        self.Message3.configure(highlightcolor="black")
        self.Message3.configure(justify='center')
        self.Message3.configure(text='''Under the Guidance of Veena N               Asst. Prof, Dept of ISE''')
        self.Message3.configure(width=250)

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.422, rely=0.815, height=34, width=127)
        self.Button1.configure(activebackground="#6fedd8")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#0ab2ef")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Consolas} -size 12")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(relief="flat")
        self.Button1.configure(text='''Get Inside''')
        self.Button1.configure(width=127)
        self.Button1.configure(command = self.operations)

    def operations(self):
        root.destroy()
        os.system('python operations.py')

if __name__ == '__main__':
    vp_start_gui()
